name: Pipeline

on: 
  push:
    branches: ['main']

env:
  APPLICATION_NAME: flexbox 
  CONTAINER_NAME: flexdeploy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "done"

  build-image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex

  deploy-on-aws:
    needs: [build-image]
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy script to S3
        run: |
          aws s3 cp bash_test.sh s3://macdo-bucket/simple-app-flexbox/ 

      - name: Add SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_LINUX }}" > ~/.ssh/aws-linux.pem
            chmod 400 ~/.ssh/aws-linux.pem

      - name: Upload file to EC2
        run: |
          scp -i ~/.ssh/aws-linux.pem -o StrictHostKeyChecking=no aws-linux.pem ec2-user@44.201.230.20:/home/ec2-user/         
            
      - name: SSH into EC2 and run bash script
        run: |
          ssh -i "~/.ssh/aws-linux.pem" ec2-user@44.201.230.20 << 'EOF'
          aws s3 cp s3://macdo_bucket/bash_test.sh /home/ec2-user/frontend_app && chmod +x /home/ec2-user/frontend_app/bash_test.sh && export DOCKER_USERNAME='${{ secrets.DOCKERHUB_USERNAME }}' && export DOCKER_PASSWORD='${{ secrets.DOCKERHUB_PASSWORD }}' && /home/ec2-user/frontend_app/bash_test.sh"
       