name: Pipeline

on: [push]
env:
  APPLICATION_NAME: flexbox
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - run: echo "done" 
  build-image:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - id: 'Auth'
       uses: 'google-github-actions/auth@v1'
       with:
           credentials_json: '${{ secrets.GCP_SERVICE_ACCT }}'
      
     - name: 'Set up Cloud SDK'
       uses: 'google-github-actions/setup-gcloud@v2'
      
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: login to docker hub
       uses: docker/login-action@v2
       with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}} 
          
     - name: build the docker image
       uses: docker/build-push-action@v4
       with:
          context: .
          file: .././Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest
   
      
