name: Pipeline

on: [push]
env:
  APPLICATION_NAME: flexbox
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - run: echo "done" 
  build-image:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - name: Set up GCloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
           credentials_json: '${{ secrets.GCP_SERVICE_ACCT }}'
      - run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud auth configure-docker
          gcloud info
    
      - name: Build and tag image
        run: docker build -t "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" .
      
      - name: Push to GCP image registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest 

  test-image:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCT }}'
      - run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud auth configure-docker
          gcloud info
        
      - name: Run unit tests in container
        run: docker run "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" -m unittest --verbose --failfast 
  deploy:
    needs: [test-image]
    runs-on: ubuntu-latest
    steps:
    - name: Set up GCloud
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCT }}'
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud info
        
    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.APPLICATION_NAME }} --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest --platform=managed --allow-unauthenticated

    - name: Test deployment
      run: |
        DEPLOY_URL=$(gcloud run services describe flexbox --platform=managed --region=us-central1 | grep https)
        curl -sL --max-time 300 -o /dev/null -w "%{http_code}" $DEPLOY_URL | grep 200 || exit 1
