 # gcloud compute firewall-rules create allow-ssh-ingress-from-iap --direction=INGRESS --action=allow  --rules=tcp:22 --source-ranges=35.235.240.0/20
  # gcloud compute start-iap-tunnel maric-instance-tp 3000 --local-host-port=localhost:  --zone=us-central1-a
  # $(gcloud info --format="value(basic.python_location)") -m pip install numpy
  # gcloud projects add-iam-policy-binding primeval-mark-378114   --member=user:rakotoarisoaromarickmacdonal@gmail.com --role=roles/iap.tunnelResourceAccessor
  name: Pipeline

  on: 
   push:
     branches: ['donal']
  env:
    APPLICATION_NAME: flexbox 
    CONTAINER_NAME: flexdeploy 
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: echo "done"
    build-image:
      needs: [lint]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
  
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex
  
    deploy-on-gcp:
      needs: [build-image] 
      name: Deploy to GCP
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.5.3
        - name: "Auth" 
          uses: "google-github-actions/auth@v1"
          with:
            credentials_json: "${{ secrets.GCP_SERVICE_ACCT }}"

        - name: "Deploy file sh to cloud storage"
          shell: 'bash'
          run: |
            gcloud storage cp bash_test.sh gs://deploy-file/frontend-script
   
        - name: "Bash"
          shell: 'bash'
          run: |
           $(gcloud info --format="value(basic.python_location)") -m pip install numpy --upgrade pip --timeout 1000
           gcloud compute ssh "instance-tp-1" --zone "us-central1-f" --tunnel-through-iap --project "primeval-mark-378114" --command="cd /home/runner/frontend_app && gcloud storage cp gs://deploy-file/frontend-script/bash_test.sh /home/runner/frontend_app && chmod +x bash_test.sh && export DOCKER_USERNAME='${{secrets.DOCKERHUB_USERNAME}}' && export DOCKER_PASSWORD='${{secrets.DOCKERHUB_PASSWORD}}' && ./bash_test.sh"     
  
