 # gcloud compute firewall-rules create allow-ssh-ingress-from-iap --direction=INGRESS --action=allow  --rules=tcp:22 --source-ranges=35.235.240.0/20
  # gcloud compute start-iap-tunnel maric-instance-tp 3389 --local-host-port=localhost:  --zone=us-central1-a
  # $(gcloud info --format="value(basic.python_location)") -m pip install numpy
name: Pipeline

on: 
 push:
   branches: ['main']
env:
  APPLICATION_NAME: flexbox
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "done"
  build-image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest

  deploy-on-gcp:
    needs: [build-image]
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCT }}"
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Bash"
        shell: 'bash'
        run: |
         gcloud compute ssh maric-instance-tp --zone=us-central1-a --command="docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest && docker run -p 5000:5000 ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest" --region=us-central1 --tunnel-through-iap --project=primeval-mark-378114  --network=default
