name: Pipeline

on: [push]
env:
  APPLICATION_NAME: flexbox
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - run: echo "done" 
  build-image:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
      - id: 'Auth'
        uses: 'google-github-actions/auth@v1'
        with:
           credentials_json: '${{ secrets.GCP_SERVICE_ACCT }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dokerfile -t maric77/${{ env.APPLICATION_NAME }}:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest
      
