name: Pipeline

on: 
  push:
    branches: ['main']

env:
  APPLICATION_NAME: flexbox 
  CONTAINER_NAME: flexdeploy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "done"

  build-image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:flex

  deploy-on-aws:
    needs: [build-image]
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: "Authentication for production"
        run: |
            aws sts get-caller-identity

      - name: Deploy script to S3
        run: |
          aws s3 cp bash_test.sh s3://macdo-bucket/simple-app-flexbox/ 
          aws s3 cp initial-script.sh s3://macdo-bucket/simple-app-flexbox/initial-script/

      - name: Add SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_LINUX }}" > ~/.ssh/aws-linux.pem
            chmod 400 ~/.ssh/aws-linux.pem

      - name: Create EC2 Launch Template for Auto Scaling
        run: |
            aws s3 cp s3://macdo-bucket/simple-app-flexbox/initial-script/initial-script.sh initial-script.sh 
            ENCODED_SCRIPT=$(base64 initial-script.sh)
            aws ec2 create-launch-template \
                --launch-template-name lunch-templante-tp \
                --tag-specifications 'ResourceType=launch-template,Tags=[{Key=Name,Value=production}]' \
                --launch-template-data '{
                    "ImageId": "ami-0182f373e66f89c85", 
                    "InstanceType": "t2.micro",
                    "KeyName": "aws-linux",
                    "UserData": "'"${ENCODED_SCRIPT}"'",
                    "Placement": {
                      "AvailabilityZone": "us-east-1a,us-east-1b"
                        },
                    "TagSpecifications": [{
                    "ResourceType": "instance",
                    "Tags": [{
                    "Key": "Name",
                    "Value": "aws-linux-instance"
                            }]
                        }]
                    }'
    
